theme = "ayu_evolve"

[editor]
line-number = "relative"
rulers = [120]
bufferline = "multiple"
popup-border = "all"
[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
# Mac Alt-o
"ø" = "expand_selection"
# Mac Alt-i
"ˆ" = "shrink_selection"
