theme = "ayu_evolve"

[editor]
line-number = "relative"
rulers = [120]
bufferline = "multiple"
popup-border = "all"
[editor.inline-diagnostics]
cursor-line = "hint"

[editor.statusline]
right = ["selections", "position", "position-percentage","spacer", "version-control"]

[keys.normal]
# Mac Alt-o
"ø" = "expand_selection"
# Mac Alt-i
"ˆ" = "shrink_selection"
[keys.normal.space]
"z" = ":buffer-close"

